"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";
import BottomNav from "../components/BottomNav";
const tierNames={standard:"Standard",vip:"VIP",vip_plus:"VIP+"};
const labels={concert:"Concert",showcase:"Showcase",conference:"Conférence",festival:"Festival"};
export default function Evenements(){
 const[category,setCategory]=useState("all"),[rows,setRows]=useState([]),[tiers,setTiers]=useState([]),[buying,setBuying]=useState(""),[msg,setMsg]=useState("Chargement des événements...");
 async function purchase(id,tier){if(!window.confirm("Confirmer l’achat du billet "+tierNames[tier]+" avec vos crédits MON PASS ?"))return;setBuying(id+tier);setMsg("Validation du billet...");const {data,error}=await supabase.rpc("buy_event_ticket",{p_offer_id:id,p_category:tier});setBuying("");if(error){setMsg(error.message);return;}setMsg("Billet acheté. Votre QR est disponible dans Mes Pass.");window.location.assign("/mes-pass");}
 useEffect(()=>{(async()=>{const {data,error}=await supabase.from("partner_offers").select("id,title,description,city,venue,starts_at,ends_at,price_fcfa,event_category,partners!inner(name,status)").eq("offer_type","event").eq("status","published").eq("partners.status","approved").order("starts_at",{ascending:true});if(error){setMsg(error.message);return;}setRows((data||[]).filter(e=>e.starts_at&&new Date(e.starts_at)>=new Date()));const {data:t}=await supabase.from("event_ticket_tiers").select("offer_id,category,price_fcfa,capacity,sold_count");setTiers(t||[]);setMsg("");})()},[]);
 const filtered=rows.filter(e=>category==="all"||e.event_category===category);
 return <main><header><a className="brand" href="/">MON <b>PASS</b></a><a className="account" href="/mes-pass">Mes Pass</a></header><section className="exploreHead"><span className="pill">ÉVÉNEMENTS MON PASS</span><h1>Concerts, showcases, conférences et festivals</h1><p>Dates, heures et lieux précis des événements proposés par nos partenaires approuvés.</p></section><section className="formWrap"><label>Filtrer les événements<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Toutes les catégories</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></section>{msg&&<p className="authMsg">{msg}</p>}<section className="offerGrid">{filtered.map(e=><article className="offerCard" key={e.id}><span className="pill">{labels[e.event_category]||"Événement"}</span><h2>{e.title}</h2><p>Organisateur : {e.partners?.name}</p><p>📅 {new Date(e.starts_at).toLocaleString("fr-FR",{dateStyle:"full",timeStyle:"short",timeZone:"Africa/Douala"})}</p><p>📍 {e.venue} · {e.city}</p>{e.description&&<p>{e.description}</p>}<div className="matchForm">{tiers.filter(t=>t.offer_id===e.id).map(t=><div key={t.category} className="reservationRow"><b>{tierNames[t.category]} · {Number(t.price_fcfa).toLocaleString("fr-FR")} FCFA</b><button className="publish" disabled={Boolean(buying)||(t.capacity!==null&&t.sold_count>=t.capacity)} onClick={()=>purchase(e.id,t.category)}>{t.capacity!==null&&t.sold_count>=t.capacity?"Complet":buying===e.id+t.category?"Achat...":"Acheter"}</button></div>)}{!tiers.some(t=>t.offer_id===e.id)&&<p>Billetterie non encore ouverte.</p>}</div></article>)}{!msg&&!filtered.length&&<p className="emptyCatalog">Aucun événement publié dans cette catégorie pour le moment.</p>}</section><BottomNav/></main>;
}