"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {supabase} from "../../../lib/supabase";
export default function MatchDetail(){
 const {id}=useParams(),[match,setMatch]=useState(null),[cats,setCats]=useState([]),[chosen,setChosen]=useState(null),[mode,setMode]=useState("buy"),[person,setPerson]=useState({name:"",phone:""}),[step,setStep]=useState("details"),[msg,setMsg]=useState("Chargement du match...");
 useEffect(()=>{if(!id)return;(async()=>{const {data,error}=await supabase.from("matches").select("id,competition,home_team,away_team,match_date,city,stadium,status,ticket_categories(id,name,price_fcfa,price_credits,min_access_credits,quantity_total,quantity_reserved)").eq("id",id).maybeSingle();setMatch(data);setCats(data?.ticket_categories||[]);setMsg(error?error.message:data?"":"Match introuvable");})()},[id]);
 function start(cat,action){setChosen(cat);setMode(action);setPerson({name:"",phone:""});setStep("details")}
 return <main><header><a className="brand" href="/">MON <b>PASS</b></a><a className="account" href="/matchs">← Matchs</a></header><section className="detailHero"><span className="pill">⚽ BILLETTERIE MATCH</span><h1>{match?.home_team||"Match"} <em>VS {match?.away_team||""}</em></h1><p>{match?.competition} · {match?.stadium} · {match?.city}</p>{match?.match_date&&<p>{new Date(match.match_date).toLocaleString("fr-FR",{dateStyle:"full",timeStyle:"short",timeZone:"Africa/Douala"})}</p>}</section><section className="booking"><h2>Choisir mon billet</h2>{msg&&<p className="authMsg">{msg}</p>}<div className="ticketTypes">{cats.map(cat=><article key={cat.id}><div><b>{cat.name}</b><p>{Math.max(0,cat.quantity_total-cat.quantity_reserved)} place(s) disponible(s)</p></div><strong>{(Number(cat.price_fcfa)+250).toLocaleString("fr-FR")} FCFA</strong><div><button type="button" disabled={cat.quantity_total<=cat.quantity_reserved} onClick={()=>start(cat,"buy")}>Payer mon ticket</button><button type="button" disabled={cat.quantity_total<=cat.quantity_reserved} onClick={()=>start(cat,"reserve")}>Réserver mon ticket</button></div></article>)}</div>{chosen&&<div className="matchForm"><h3>{mode==="reserve"?"Réserver mon ticket":"Payer mon ticket"} · {chosen.name}</h3><p>Match : {match?.home_team} VS {match?.away_team}</p><p>Catégorie : {chosen.name} · <b>{(Number(chosen.price_fcfa)+250).toLocaleString("fr-FR")} FCFA</b></p>{step==="details"?<form onSubmit={e=>{e.preventDefault();setStep("review")}}><label>Nom complet<input required minLength="2" value={person.name} onChange={e=>setPerson(s=>({...s,name:e.target.value}))}/></label><label>Téléphone<input required type="tel" minLength="8" value={person.phone} onChange={e=>setPerson(s=>({...s,phone:e.target.value}))}/></label><button type="submit">Continuer vers le paiement</button></form>:<div><h3>Récapitulatif</h3><p>Client : {person.name}</p><p>Téléphone : {person.phone}</p><p>Billet : {chosen.name}</p><p>Total (dont 250 FCFA de frais MON PASS) : {(Number(chosen.price_fcfa)+250).toLocaleString("fr-FR")} FCFA</p><button type="button" disabled title="Paiement CinetPay non connecté">Confirmer et payer — bientôt disponible</button><p className="authMsg">Aucun paiement ni réservation n'a été enregistré. La confirmation sécurisée du paiement sera intégrée ensuite.</p><button type="button" onClick={()=>setStep("details")}>Modifier les informations</button></div>}<button type="button" onClick={()=>setChosen(null)}>Fermer</button></div>}</section></main>
}